title: Manoa Market
description: Profiles, Projects, and Interests for the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-modernist
github:
  is_project_page: true
  repository_url: 
gems:
  - jekyll-mentions
