title: Manoa Market
description: A place for UH affiliated people to buy and sell things.
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: 
gems:
  - jekyll-mentions
